name: meeme-frontend CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:

    runs-on: self-hosted

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2
       
    # - name: copy Env
    #  run: cp /.env /actions-runner/_work/meeme-frontend/meeme-frontend

    - name: install node Modules 
      run: npm install
      
    - name: Creating Build using npm manager
      run: npm run build
      env:
        CI: false
         
    - name: copy htaccess
      run: cp /.htaccess /var/www/actions-runner/_work/meeme-frontend/meeme-frontend/build
      
