name: meeme-frontend CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:

    runs-on: self-hosted

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2
       
    # - name: copy Env
    #  run: cp /.env /actions-runner/_work/meeme-frontend/meeme-frontend

    - name: build
      run: yarn build
         
    - name: copy htaccess
      run: cp /.htaccess /actions-runner/_work/meeme-frontend/meeme-frontend
      
